# Dev environment configuration
spring:
  application:
    name: dojo-dev
  config:
    activate:
      on-profile: dev
  
  # Datasource configuration using docker-compose postgres service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dojodb}
    username: ${DB_USERNAME:dojo}
    password: ${DB_PASSWORD:dojo123}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # AWS Configuration - LocalStack
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-west-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
      endpoint: ${AWS_ENDPOINT_URI:http://localhost:4566}
      # S3 configuration
      s3:
        endpoint: ${AWS_S3_ENDPOINT_URI:http://localhost:4566}
        path-style-access-enabled: true

# Custom app properties for S3
app:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:dojo-bucket}
    
# Logging
logging:
  level:
    '[com.delimce.aws.dojo]': DEBUG
    '[io.awspring.cloud]': DEBUG
    '[software.amazon.awssdk.services.s3]': DEBUG
