# Dev environment configuration
spring:
  application:
    name: dojo-dev
  config:
    activate:
      on-profile: dev
  
  # Datasource configuration using docker-compose postgres service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dojodb}
    username: ${DB_USERNAME:dojo}
    password: ${DB_PASSWORD:dojo123}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # AWS Configuration - LocalStack
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-west-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
      endpoint: ${AWS_ENDPOINT_URI:http://localhost:4566}

# AWS configuration is now simplified
# No service-specific configurations

# Logging
logging:
  level:
    '[com.delimce.aws.dojo]': DEBUG
    '[io.awspring.cloud]': DEBUG
